---
title: "Gráficos"
author: "Beatriz Magiore"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(rcartocolor)
```


## GGPLOT

O conjunto de dados \textit{\textbf{Pokemon}} é composto de variáveis quantitativas e qualitativas. A tabela a seguir mostra o resumo dos dados:

```{r, echo=FALSE}
dados <- read.csv("Dados/Pokemon_full.csv")
summary(dados)
```

# Box-plot

```{r, fig.align='center'}

df <-  dados %>% 
  mutate(
    classe_altura = case_when(
      height < 5 ~ "Baixinho",
      height < 50 ~ "Pequeno",
      height < 100 ~ "Médio",
      TRUE ~ "Altão"
    )
  ) %>% 
  mutate(
    classe_altura = factor(classe_altura, 
                           levels = c("Baixinho", "Pequeno", "Médio", "Altão"))
  )

ggplot(df, aes(x = classe_altura, y = weight, fill = classe_altura))+
  geom_violin()+
  geom_boxplot(width = 0.2, fill = "white")+
    labs(
      x = "Classe altura",
      y = "Peso"
    )+
    scale_y_continuous(trans = "log10")+
    theme_minimal()+
    theme(
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 13,face = "bold"),
      legend.position = "none"
    )

```

# Gráfico de pontos

```{r, fig.align='center'}
df %>% 
  arrange(desc(classe_altura)) %>% 
  ggplot(aes(x = weight, y = height, color = classe_altura))+
  geom_point()+
    labs(
      x = "Peso",
      y = "Altura",
      color = "Classe altura"
    )+
    guides(color = guide_legend(override.aes = list(size = 3)))+
    scale_x_continuous(trans = "log10")+
    scale_y_continuous(trans = "log10")+
    theme_minimal()+
    theme(
      axis.text = element_text(size = 11),
      axis.title = element_text(size = 13, face = "bold"),
      legend.position = "right",
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 11, face = "bold")
    )
```

